Repository neg4n/next-api-compose, pull requests merged in 2023-10, with the labels that each got.

#13 Update README
  .github/README.md
Labels: documentation

#14 Create unit tests
  packages/next-api-compose/jest.config.js
  packages/next-api-compose/jest.setup.js
  packages/next-api-compose/package.json
  packages/next-api-compose/test/app.test.ts
  packages/next-api-compose/test/inference.ts
  pnpm-lock.yaml
Labels: enhancement, ci, tests

#15 Enhance tests + configure CI
  .github/README.md
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  packages/next-api-compose/package.json
  packages/next-api-compose/test/app.test.ts
  packages/next-api-compose/test/inference.ts
  packages/next-api-compose/test/pages.test.ts
  pnpm-lock.yaml
  turbo.json
Labels: enhancement, ci, tests

#16 Integrate all-contributors bot
  .all-contributorsrc
  README.md
Labels: documentation, enhancement

#17 Update next-api-compose package description + docs
  packages/next-api-compose/package.json
Labels: documentation, enhancement
